research_task:
  description: >
    Where is the vehicle "Red truck" & how many hours have the driver driven this vehicle
  expected_output: >
    The latitude & longitude of the vehicle and also the driver time of the driver driving this vehicle
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
